### ISSUE TITLE
Question on header name case-sensitivity 

### ISSUE THREAD

**Issue by IDisposable** [kwhitley/itty-cors#11]
On line [#75](https://github.com/kwhitley/itty-cors/blob/v0.x/src/itty-cors.ts#L74) we have `existingHeaders['access-control-allow-origin'] ` but on line [#34](https://github.com/kwhitley/itty-cors/blob/v0.x/src/itty-cors.ts#L34) it's ` 'Access-Control-Allow-Origin'` which seem likely to be a problem... is the `existingHeaders` key lookup magically case-insensitive?

**Comment by kwhitley** [comment]
https://developer.mozilla.org/en-US/docs/Web/HTTP/Headers

Headers are case-insensitive!  That said, I should probably unify the example at least :)
