### ISSUE TITLE
Support missing response

### ISSUE THREAD

**Issue by danew** [kwhitley/itty-cors#5]
The `corsify` function throws a `TypeError` if the function is called without a response.

Instead, I believe the handler should check if the response exists first and if not throw an appropriate error.

Cloudflare workers throws: 
```
[mf:err] POST /nada: FetchError [ERR_NO_RESPONSE]: No fetch handler responded and no upstream to proxy to specified.
Make sure you're returning a `Response` in your handler.
```

**Comment by kwhitley** [comment]
Addressed in #6
